# Generated by Django 3.2.9 on 2021-11-30 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=350, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(verbose_name=datetime.datetime.now)),
                ('note', models.CharField(max_length=300)),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_do', to='account.customuser')),
            ],
        ),
    ]
